language: objective-c
osx_image: xcode8.3
install:
- gem install xcpretty
script:
- xcodebuild -project YYTun2Socks.xcodeproj -scheme "iOS YYTun2Socks" | xcpretty
- xcodebuild -project YYTun2Socks.xcodeproj -scheme "macOS YYTun2Socks" | xcpretty
after_success:
- "./docs/build_docs.sh"
before_deploy:
- carthage build --no-skip-current
- carthage archive YYTun2Socks
deploy:
  provider: releases
  api_key: cbf435cf4bec5ba64dba0046e1a949b3d3882051
  file: YYTun2Socks.framework.zip
  skip_cleanup: true
  on:
    repo: Hmyy/YYTun2Socks
    tags: true

