language: objective-c
osx_image: xcode8.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
install:
- gem install xcpretty
script:
- xcodebuild -project YYTun2Socks.xcodeproj -scheme "iOS YYTun2Socks" | xcpretty
- xcodebuild -project YYTun2Socks.xcodeproj -scheme "macOS YYTun2Socks" | xcpretty
after_success:
- "./docs/build_docs.sh"
before_deploy:
- carthage build --no-skip-current
- carthage archive YYTun2Socks
